# Generated by Django 3.0.3 on 2020-02-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('category', models.TextField()),
                ('brand', models.CharField(max_length=200)),
                ('brand_link', models.URLField(max_length=300)),
                ('img', models.URLField(max_length=300)),
                ('details', models.TextField()),
                ('nutigrade', models.CharField(max_length=2)),
                ('nutriscore', models.IntegerField()),
                ('stores', models.TextField()),
                ('link', models.URLField(max_length=300)),
                ('ingredients', models.TextField()),
                ('fat_100g', models.FloatField()),
                ('saturated_fat_100g', models.FloatField()),
                ('salt_100g', models.FloatField()),
                ('sugar_100g', models.FloatField()),
                ('nova', models.IntegerField()),
            ],
            options={
                'verbose_name': 'product',
                'ordering': ['name'],
            },
        ),
    ]
