# Generated by Django 3.0.3 on 2020-02-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=200, unique=True)),
                ('nutigrade', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
