# Generated by Django 3.0.3 on 2020-03-05 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('img', models.URLField(max_length=300)),
                ('category', models.TextField()),
                ('details', models.TextField()),
                ('brand', models.CharField(max_length=200)),
                ('brand_link', models.URLField(max_length=300)),
                ('nutrigrade', models.CharField(max_length=2)),
                ('nutriscore', models.IntegerField()),
                ('stores', models.TextField()),
                ('link', models.URLField(max_length=300)),
                ('ingredients', models.TextField()),
                ('fat_100g', models.FloatField()),
                ('saturated_fat_100g', models.FloatField()),
                ('level_saturated_fat', models.CharField(max_length=30)),
                ('salt_100g', models.FloatField()),
                ('level_salt', models.CharField(max_length=30)),
                ('sugar_100g', models.FloatField()),
                ('level_sugar', models.CharField(max_length=30)),
                ('nova', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saved_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Favorite')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
