# Generated by Django 3.0.3 on 2020-03-08 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200305_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='brand_link',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='category',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='fat_100g',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='level_salt',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='level_saturated_fat',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='level_sugar',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='link',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='nova',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='nutriscore',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='salt_100g',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='saturated_fat_100g',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='sugar_100g',
        ),
        migrations.AddField(
            model_name='favorites',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date sauvegarde'),
        ),
    ]
