# Generated by Django 3.0.3 on 2020-03-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200308_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('img', models.URLField(max_length=300)),
                ('details', models.TextField()),
                ('nutrigrade', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='favorites',
            name='saved_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
