# Generated by Django 3.0.3 on 2020-03-08 08:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_auto_20200308_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='FavoriteProduct',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='SavedProduct',
        ),
    ]
