# Generated by Django 3.0.3 on 2020-03-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200308_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteproduct',
            old_name='saved_by',
            new_name='user',
        ),
    ]
