# Generated by Django 3.0.3 on 2020-03-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200308_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('img', models.URLField(max_length=300)),
                ('details', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('nutrigrade', models.CharField(max_length=2)),
                ('ingredients', models.TextField()),
                ('fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('salt', models.FloatField()),
                ('sugar', models.FloatField()),
                ('level_fat', models.CharField(max_length=50)),
                ('level_saturated_fat', models.CharField(max_length=50)),
                ('level_salt', models.CharField(max_length=50)),
                ('level_sugar', models.CharField(max_length=50)),
            ],
        ),
    ]
