# Generated by Django 3.0.3 on 2020-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200314_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
