# Generated by Django 3.0.3 on 2020-03-15 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_products_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
