# Generated by Django 3.0.3 on 2020-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_updatereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatereport',
            name='added',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updatereport',
            name='duration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updatereport',
            name='keeped',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updatereport',
            name='rejected',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updatereport',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
