# Generated by Django 3.0.3 on 2020-03-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200315_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatereport',
            name='date',
        ),
    ]
