# Generated by Django 3.0.3 on 2020-03-15 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_updatereport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatereport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
