# Generated by Django 3.0.3 on 2020-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_updatereport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='nova',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
