# Generated by Django 3.0.3 on 2020-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_products_nova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
