# Generated by Django 3.0.3 on 2020-03-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200316_1844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='BaseProduct',
        ),
    ]
